packages:
  - "packages/*"
  - "playgrounds/*"

autoInstallPeers: false
injectWorkspacePackages: true
resolvePeersFromWorkspaceRoot: false
peerDependencyRules:
  allowedVersions:
    "eslint-plugin-solid>eslint": "^9.0.0 || ^10.0.0"
    "tsconfck>typescript": "^5.0.0 || ^6.0.0"
syncInjectedDepsAfterScripts:
  - build
